# Generated by Django 2.1.5 on 2019-01-15 16:38

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(default='', max_length=1000)),
                ('author_text', models.CharField(default='Anonymus', max_length=100)),
                ('article_text', markdownx.models.MarkdownxField()),
                ('published_date', models.DateField(default=datetime.datetime.now)),
                ('slug_title_text', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='articlemodel',
            unique_together={('title_text', 'author_text', 'published_date')},
        ),
    ]
